language: python
os: linux
dist: bionic
addons:
  apt:
    packages:
      - libspatialindex-dev
cache:
  - cargo
  - pip

stages:
  - test
  - name: deploy
    if: tag IS present
env:
  global:
  - TRAVIS_RUST_VERSION=nightly-2020-05-01
  - RUST_BACKTRACE=1

test_template: &test_template
  stage: test
  before_install:
    - source ./ci/travis/setup_rust.sh
  install:
    - pip install -r requirements.txt
    - maturin develop --release
  script:
    - pytest -v --benchmark-skip
    - flake8 .
    - black --check .

jobs:
  include:
    - name: "Rust tests"
      stage: test
      before_install: source ./ci/travis/setup_rust.sh
      script:
        - cargo test
        - cargo fmt -- --check
        - cargo clippy
    - <<: *test_template
      python: 3.7
    - <<: *test_template
      python: 3.8
    - stage: deploy
      before_install: source ./ci/travis/setup_rust.sh
      install: pip install $(grep '^maturin' requirements.txt)
      script: maturin publish -u __token__ -p $PYPI_TOKEN -i python3.8 -i python3.7
