language: python
dist: xenial
addons:
    apt:
      packages:
        - libspatialindex-dev

stages:
  - test
  - name: deploy
    if: tag IS present
env:
  global:
  - TRAVIS_RUST_VERSION=nightly-2020-05-01
  - RUST_BACKTRACE=1
  - PYPI_USERNAME=clbarnes

test_template: &test_template
  stage: test
  before_install:
    - source ./ci/travis/setup_rust.sh
  install:
    - pip install -r requirements.txt
  script:
    - pytest -v
    - flake8 .

deploy_template: &deploy_template
  stage: deploy
  before_install:
    - source ./ci/travis/setup_rust.sh
  install:
    - pip install -r requirements.txt
  script:
    ./ci/travis/deploy.sh

jobs:
  include:
    - name: "rust tests"
      stage: test
      before_install: source ./ci/travis/setup_rust.sh
      script:
        - cargo test
        - cargo fmt -- --check
        - cargo clippy
    - <<: *test_template
      python: 3.7
    - <<: *test_template
      python: 3.8
    - <<: *deploy_template
      python: 3.7
    - <<: *deploy_template
      python: 3.8
